version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - policy-reports
      - webquotes

  policy-reports:
    image: policy-reports:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  webquotes:
    image: webquotes:latest
    deploy:
      mode: replicated
      replicas: 1